### ISSUE TITLE
materials list should include optional and "required" components

### ISSUE THREAD

**Issue by kmaull-ucar** [NCAR/openiotwx#1]
https://ncar.github.io/openiotwx/getting-started/materials/

For example, there are optional printing items, like:

- PEI sheet for better printing surface

And it isn't clear, which items in the base station should be purchased:
- a base system could be configured with a 10w panel v25 battery
- the base system should include the 4x4x4 (e.g. https://www.homedepot.com/p/4-in-x-4-in-x-4-in-Junction-Box-R5133709/202043437 or https://www.amazon.com/Cantex-5133709U-Junction-Box/dp/B01HCJDHUQ or https://www.gordonelectricsupply.com/p/Cantex-5133709-4X4X4-Pvc-Jct-Box/6043582)

**Comment by ralter** [comment]
Added these - good enough? happy to switch off.
